### ISSUE TITLE
No matching machine found for Windows

### ISSUE THREAD

**Issue by schugs4** [SymfonyCasts/sass-bundle#11]
In SassBinary.php line 150:

  [Exception]
  No matching machine found for Windows platform (Machine: i586).

**Comment by schugs4** [comment]
I can solve it locally by adding that machine type to the "if ('x86_64' === $machine || 'amd64' === $machine)" (SassBinary.php -line 146),

**Comment by bocharsky-bw** [comment]
Hey @schugs4 ,

Yeah, there might be some edge cases that are not covered in that spot! Thanks for sharing more feedback about it and taking the time to report this issue. Do you want to create a PR to include that Machine on the list? Or just let us know and we will do it ourselves :)

**Comment by schugs4** [comment]
Honestly, this will be my first time trying an official pull request. Let me give it a go and see if i can do it easy enough!

**Comment by weaverryan** [comment]
Great job - thanks for making the PR!
