### ISSUE TITLE
dart executable not found, but it's definitely there

### ISSUE THREAD

**Issue by viu-x** [SymfonyCasts/sass-bundle#27]
I tried to deploy my local project to my hoster and the `sass:build` command is failing.

![Bildschirmfoto 2023-10-30 um 15 15 02](https://github.com/SymfonyCasts/sass-bundle/assets/103430706/73bb0c34-95c8-4ed2-a74c-bb3739f5b846)

I think I'm missing something very obvious but cannot see it. As the screenshot shows it errors that the file `/html/releases/19/var/dart-sass/src/dart` is not found. But that file is definitely there. I even tried with different rights (755, 777, 700) but always with the same outcome.

On my local DDEV project that command runs fine inside the container.

What am I not seeing?

**Comment by WebMamba** [comment]
Are you running the sass:build command inside or outside your container? If the binary is inside your container you should run `docker composer php bin/console sass:build`.
The issue can be also if you use alpine the sass binary is not compatible

**Comment by viu-x** [comment]
Sorry, forgot to close this issue. Figured it out with my hoster. Initially this command ran during deployment directly on their machine, where some lib wasn't present. I then ran it inside the pipeline and copied the resulting files to the host server.

So consider it closed.

**Comment by WebMamba** [comment]
Do you use alpine js? Because you can may help on this: #31

**Comment by viu-x** [comment]
> Do you use alpine js? Because you can may help on this: #31

Nope, my pipeline runs on `ubuntu-latest`.
