### ISSUE TITLE
[CS] Test errors

### ISSUE THREAD

**Issue by smnandre** [SymfonyCasts/sass-bundle#53]
I'm not able to reproduce the CI errors locally ... and it seems to me when the option PR was merged it worked.

If someone here can help me figure out what's happening and how to fix it ? 

🙏

**Comment by bocharsky-bw** [comment]
Hm, probably a random fail? I will restart the failed jobs to see if it helps

**Comment by smnandre** [comment]
Thanks, that was probably a glitch! https://github.com/SymfonyCasts/sass-bundle/actions/runs/7389012804
