### ISSUE TITLE
Make the sourcemap available

### ISSUE THREAD

**Issue by weaverryan** [SymfonyCasts/sass-bundle#6]
When the package builds, a `.map` file is output. But, we're not currently making it available.

Another option is to pass `--embed-source-map` and embed it directly in the CSS file (in `dev` mode only).

**Comment by schugs4** [comment]
Is this a symtom where the bundle builds a compiled correctly css file in var/sass/* but asset-mapper is still just serving a temp file that is an exact replica of the orginal scss? That is what i am getting, not sure what i am missing.

**Comment by weaverryan** [comment]
Hey!

First, I just added some details about excluding paths - https://github.com/SymfonyCasts/sass-bundle/commit/8153fd60032c3de0b8535daa7b3bb4e326756bf7 - be careful you're not excluding your actual `app.scss` file.

Anyway, I bet this is the problem: https://github.com/SymfonyCasts/sass-bundle/pull/14

**Comment by schugs4** [comment]
Confirming that 2.2 resolved the issue i was having. Thanks!

Related to your note, i have two questions, 
1.) Does the bundle always only look at assets/styles/app.scss?  When i tried moving it to assets/app.scss app threw an error that it couldn't find assets/styles/app.scss?
2.) The reason i wanted to move it was to add the assets/styles to the exclude list and just have one scss file at the root, in the comments you added  in 8153fd6 i dont understand how that wouldnt exclude assets/styles/app,scss.  Is there a recomended exclude statement that excludes others but NOT app.scss?
