### ISSUE TITLE
Fix: Allow custom root_sass to be relative paths

### ISSUE THREAD

**Issue by weaverryan** [SymfonyCasts/sass-bundle#8]
See: https://github.com/SymfonyCasts/tailwind-bundle/pull/22

Also, this option is undocumented and should be documented.

AND, if the user just does:

```
root_sass: 'assets/styles/foo.scss'
```

We should normalize that into an array for them

**Comment by weaverryan** [comment]
I just tripped over this in my own project, lol.

For SassBundle, we also need to be careful that the compiler is adjusted. IIrc, I COULD `sass:build` just fine with a relative path. But the path comparison in `supports()` of the compiler failed with a relative path.

**Comment by bocharsky-bw** [comment]
Closed with #64
