### ISSUE TITLE
Option to force download instead of using local binary

### ISSUE THREAD

**Issue by Huluti** [SymfonyCasts/sass-bundle#80]
It would be nice to have an option to ignore locally installed package (for example useful if too old) and force the download.

Thanks!

**Comment by bocharsky-bw** [comment]
If the bundle downloads bin and then just constantly uses that downloaded version even when a new version is released - this idea makes sense to me. Though I'm not sure if it's the best solution. Btw, as a workaround, you can just manually remove that bin and then the bundle will download a fresh version for you.

**Comment by Huluti** [comment]
Yeah make sense!

For me to was because the sass package was installed by the cloud provider with no way to remove it.

Anyway I doesn't need this anymore, I've converted my files into pure CSS.

Feel free to close the PR :)

**Comment by sadikoff** [comment]
#42 should help somehow, or maybe it can be expanded with some usable options, so closing it for now
